### ISSUE TITLE
Version 0.0.1 checklist

### ISSUE THREAD

**Issue by epicallan** [pacthq/bounded#1]
- [x] Add examples
- [ ] Add haddock docs
- [x] Add type level tests
- [ ] format with a formatter and integrate into test suite
- [x] Make readme runnable (testable)
- [ ] Write accompanying blog
- [x] Drop HasBound and use partial class
- [x] Add type safe checked construction of bound types
